const colors={trekking:"#176b4a",walk:"#176b4a",cammino:"#6e4ab5",bicycle:"#117b93",mtb:"#315b9d"};
const VERSILIA_DEFAULT_CENTER=[43.95,10.25];
const VERSILIA_DEFAULT_ZOOM=11.25;
const VERSILIA_HOME_BOUNDS=[[43.765,10.105],[44.125,10.455]];
const VERSILIA_CONTEXT_BOUNDS=[[43.75,10.10],[44.12,10.52]];
const state={features:[],filtered:[],layers:new Map(),selected:null,mode:"all",municipality:"",search:"",versiliaBounds:null,municipalityBounds:new Map()};
let map,routesLayer,muniLayer;
function fmtKm(v){const n=Number(v);return Number.isFinite(n)?`${n.toLocaleString("it-IT",{maximumFractionDigits:1})} km`:"—"}
function modesLabel(p){const m=p.modalities||[],out=[];if(m.includes("trekking"))out.push("trekking");if(m.includes("cammino"))out.push("cammino");if(m.includes("bicycle"))out.push("bici");if(m.includes("mtb"))out.push("MTB");if(!out.length&&m.includes("walk"))out.push("a piedi");return out.join(" · ")}
function qualityClass(q){return q==="A0"?"a0":"b1"}
function qText(q){return q==="A0"?"Ufficiale":"Corroborato"}
function styleFeature(f,selected=false){const p=f.properties||{},pm=p.primary_mode||"trekking",c=colors[pm]||colors.trekking;return{color:c,weight:selected?6:4,opacity:selected?1:.9,dashArray:null,lineCap:"round",lineJoin:"round"}}
function updateLocalDiag(){}
function initMap(){map=L.map("map",{zoomControl:true,preferCanvas:true,zoomSnap:.25,zoomDelta:.25}).setView(VERSILIA_DEFAULT_CENTER,VERSILIA_DEFAULT_ZOOM,{animate:false});L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(map);routesLayer=L.layerGroup().addTo(map);muniLayer=L.layerGroup().addTo(map);addHomeControl();const settle=()=>{map.invalidateSize({animate:false});if(!state.selected&&!state.municipality)map.setView(VERSILIA_DEFAULT_CENTER,VERSILIA_DEFAULT_ZOOM,{animate:false})};requestAnimationFrame(settle);[120,400,900].forEach(ms=>setTimeout(settle,ms));window.addEventListener("resize",()=>{map.invalidateSize({animate:false});if(!state.selected&&!state.municipality)map.setView(VERSILIA_DEFAULT_CENTER,VERSILIA_DEFAULT_ZOOM,{animate:false})})}
async function loadBoundaries(){}
function addHomeControl(){const HomeControl=L.Control.extend({options:{position:"topleft"},onAdd(){const container=L.DomUtil.create("div","leaflet-control-home leaflet-bar"),link=L.DomUtil.create("a","",container);link.href="#";link.title="Home: torna alla vista generale Versilia";link.setAttribute("aria-label","Home: torna alla vista generale Versilia");link.innerHTML="<span>⌂</span>";L.DomEvent.disableClickPropagation(container);L.DomEvent.on(link,"click",ev=>{L.DomEvent.stop(ev);fitVersilia()});return container}});map.addControl(new HomeControl())}
function buildMunicipalityBounds(){state.municipalityBounds.clear();const context=L.latLngBounds(VERSILIA_CONTEXT_BOUNDS);state.features.forEach(f=>{const municipalities=f.properties?.municipalities||[],coords=[];const walk=c=>{if(!Array.isArray(c))return;if(typeof c[0]==="number"&&typeof c[1]==="number"){const p=L.latLng(c[1],c[0]);if(context.contains(p))coords.push(p);return}c.forEach(walk)};walk(f.geometry?.coordinates);if(!coords.length)return;municipalities.forEach(name=>{const b=state.municipalityBounds.get(name)||L.latLngBounds([]);coords.forEach(p=>b.extend(p));state.municipalityBounds.set(name,b)})})}
function fitVersilia(){map.stop();map.invalidateSize({animate:false});map.setView(VERSILIA_DEFAULT_CENTER,VERSILIA_DEFAULT_ZOOM,{animate:false})}
function fitFilterContext(){const mb=state.municipality?state.municipalityBounds.get(state.municipality):null;if(mb?.isValid())map.fitBounds(mb.pad(.08),{padding:[25,25],maxZoom:13,animate:false});else fitVersilia()}
function stabilizeInitialViewport(){[0,150,500,1000].forEach(delay=>setTimeout(()=>{if(!state.selected&&!state.municipality){map.invalidateSize({animate:false});map.setView(VERSILIA_DEFAULT_CENTER,VERSILIA_DEFAULT_ZOOM,{animate:false})}},delay))}
function clearSelection(fit=false){state.selected=null;document.getElementById("detail").classList.remove("show");state.layers.forEach(layer=>layer.eachLayer(x=>x.setStyle(styleFeature(x.feature,false))));renderList();if(fit)fitFilterContext()}
function collectLatLngs(x,out=[]){if(!x)return out;if(Array.isArray(x)){x.forEach(v=>collectLatLngs(v,out));return out}if(typeof x.lat==="number"&&typeof x.lng==="number")out.push(x);return out}
function contextualRouteBounds(layer){if(!layer)return null;const context=L.latLngBounds(VERSILIA_CONTEXT_BOUNDS),pts=[];layer.eachLayer(l=>collectLatLngs(l.getLatLngs?.(),pts));const inside=pts.filter(p=>context.contains(p));if(!inside.length)return null;const b=L.latLngBounds(inside);return b.isValid()?b:null}
function decodePolyline(encoded,precision=5){let index=0,lat=0,lon=0,coords=[],factor=10**precision;while(index<encoded.length){let result=0,shift=0,b;do{b=encoded.charCodeAt(index++)-63;result|=(b&31)<<shift;shift+=5}while(b>=32);lat+=(result&1)?~(result>>1):(result>>1);result=0;shift=0;do{b=encoded.charCodeAt(index++)-63;result|=(b&31)<<shift;shift+=5}while(b>=32);lon+=(result&1)?~(result>>1):(result>>1);coords.push([lon/factor,lat/factor])}return coords}
function decodeRoute(record){const lines=(record.l||[]).map(line=>decodePolyline(line,5));return{type:"Feature",properties:record.p||{},geometry:lines.length===1?{type:"LineString",coordinates:lines[0]}:{type:"MultiLineString",coordinates:lines}}}
async function loadData(){try{const partUrls=Array.from({length:7},(_,i)=>`data/compact-${String(i).padStart(2,"0")}.json`);const[parts,s]=await Promise.all([Promise.all(partUrls.map(url=>fetch(url,{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error(`Dataset percorsi non trovato: ${url}`);return r.json()}))),fetch("data/master_summary.json",{cache:"no-store"})]);state.features=parts.flat().map(decodeRoute);let summary={};try{summary=await s.json()}catch(e){}document.getElementById("totalRoutes").textContent=state.features.length;document.getElementById("totalKm").textContent=(summary.public_versilia_km??summary.public_total_km??0).toLocaleString("it-IT",{maximumFractionDigits:0});populateMunicipalities();buildMunicipalityBounds();applyFilters(false);fitVersilia()}catch(e){document.getElementById("routeList").innerHTML=`<div class="errorBox">${e.message}</div>`}}
function populateMunicipalities(){const set=new Set();state.features.forEach(f=>(f.properties?.municipalities||[]).forEach(x=>set.add(x)));const sel=document.getElementById("municipality");[...set].sort((a,b)=>a.localeCompare(b,"it")).forEach(x=>{const o=document.createElement("option");o.value=x;o.textContent=x;sel.appendChild(o)})}
function matches(f){const p=f.properties||{},q=state.search.trim().toLocaleLowerCase("it");if(state.mode!=="all"&&!(p.modalities||[]).includes(state.mode)&&p.primary_mode!==state.mode)return false;if(state.municipality&&!(p.municipalities||[]).includes(state.municipality)return false;if(q){const hay=[p.name,p.ref,p.category,(p.municipalities||[]).join(" "),p.network_name].filter(Boolean).join(" ").toLocaleLowerCase("it");if(!hay.includes(q))return false}return true}
function applyFilters(fit=false){state.filtered=state.features.filter(matches);document.getElementById("resultsCount").textContent=`${state.filtered.length} risultati`;renderList();renderMap(fit)}
function renderMap(fit=false){routesLayer.clearLayers();state.layers.clear();state.filtered.forEach(f=>{const l=L.geoJSON(f,{style:styleFeature(f,false),onEachFeature:(ff,ll)=>{ll.on("click",()=>selectRoute(ff.properties.id,true))}});l.addTo(routesLayer);state.layers.set(f.properties.id,l)});if(fit)fitFilterContext()}
function routeCard(f){const p=f.properties||{},mode=p.primary_mode||"trekking",c=colors[mode]||colors.trekking,km=fmtKm(p.length_km),muni=(p.municipalities||[]).join(", ")||"Versilia",active=state.selected===p.id?" active":"";return `<article class="card${active}" data-id="${p.id}"><div class="cardTop"><div class="routeName">${escapeHtml(p.name||"Percorso")}</div><span class="badge ${qualityClass(p.quality_code)}">${qText(p.quality_code)}</span></div><div class="meta"><span><i class="modeDot" style="background:${c}"></i>${modesLabel(p)}</span><span>${km}</span><span>${escapeHtml(muni)}</span></div></article>`}
function renderList(){const el=document.getElementById("routeList");if(!state.filtered.length){el.innerHTML='<div class="empty">Nessun percorso con questi filtri.</div>';return}el.innerHTML=state.filtered.map(routeCard).join("");el.querySelectorAll(".card").forEach(c=>c.addEventListener("click",()=>selectRoute(c.dataset.id,true)))}
function selectRoute(id,zoom=true){const f=state.features.find(x=>x.properties?.id===id);if(!f)return;state.selected=id;renderList();state.layers.forEach((layer,k)=>layer.eachLayer(x=>x.setStyle(styleFeature(x.feature,k===id))));const layer=state.layers.get(id);if(zoom&&layer){const b=contextualRouteBounds(layer);if(b)map.fitBounds(b,{padding:[50,50],maxZoom:14});else fitVersilia()}const p=f.properties||{};document.getElementById("detailName").textContent=p.name||"Percorso";document.getElementById("detailSub").textContent=[modesLabel(p),p.category].filter(Boolean).join(" · ");document.getElementById("detailKm").textContent=fmtKm(p.length_km);document.getElementById("detailDifficulty").textContent=p.difficulty||"—";document.getElementById("detailComuni").textContent=(p.municipalities||[]).join(", ")||"—";document.getElementById("detailQuality").textContent=p.quality_label||qText(p.quality_code);const src=p.source_url?`Fonte: <a href="${p.source_url}" target="_blank" rel="noopener">${escapeHtml(p.source_authority||"fonte istituzionale")} ↗</a>`:`Fonte: ${escapeHtml(p.source_authority||"fonte istituzionale")}`;const note=p.quality_code==="B1"?" · Geometria ricostruita su OSM e corroborata da fonte istituzionale.":"";const outside=p.continues_outside_versilia?" · <strong>Prosegue fuori Versilia:</strong> la traccia completa è mostrata, ma l’inquadratura resta sui 7 Comuni.":"";document.getElementById("detailSource").innerHTML=src+note+outside;document.getElementById("detail").classList.add("show")}
function geometryLines(geometry){if(!geometry)return[];if(geometry.type==="LineString")return[geometry.coordinates];if(geometry.type==="MultiLineString")return geometry.coordinates;return[]}
function xmlEscape(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[m]))}
function featurePayload(feature,format){const p=feature.properties||{},name=p.name||"Percorso",lines=geometryLines(feature.geometry);if(format==="geojson")return{mime:"application/geo+json",ext:"geojson",text:JSON.stringify(feature,null,2)};if(format==="gpx"){const segs=lines.map(line=>`<trkseg>${line.map(c=>`<trkpt lat="${c[1]}" lon="${c[0]}"></trkpt>`).join("")}</trkseg>`).join("");return{mime:"application/gpx+xml",ext:"gpx",text:`<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="Osservatorio Versilia" xmlns="http://www.topografix.com/GPX/1/1"><trk><name>${xmlEscape(name)}</name>${segs}</trk></gpx>`}}const geom=lines.map(line=>`<LineString><tessellate>1</tessellate><coordinates>${line.map(c=>`${c[0]},${c[1]},0`).join(" ")}</coordinates></LineString>`).join("");return{mime:"application/vnd.google-earth.kml+xml",ext:"kml",text:`<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><Placemark><name>${xmlEscape(name)}</name><MultiGeometry>${geom}</MultiGeometry></Placemark></Document></kml>`}}
function slugFile(s){return String(s||"percorso").toLocaleLowerCase("it").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function triggerDownload(payload,filename){const blob=new Blob([payload.text],{type:payload.mime}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function downloadSelected(format){const f=state.features.find(x=>x.properties?.id===state.selected);if(!f)return;const payload=featurePayload(f,format);triggerDownload(payload,`${slugFile(f.properties?.name)}.${payload.ext}`)}
function collectionPayload(features,format){if(format==="geojson")return{mime:"application/geo+json",ext:"geojson",text:JSON.stringify({type:"FeatureCollection",features})};if(format==="gpx"){const tracks=features.map(f=>{const name=f.properties?.name||"Percorso",segs=geometryLines(f.geometry).map(line=>`<trkseg>${line.map(c=>`<trkpt lat="${c[1]}" lon="${c[0]}"></trkpt>`).join("")}</trkseg>`).join("");return `<trk><name>${xmlEscape(name)}</name>${segs}</trk>`}).join("");return{mime:"application/gpx+xml",ext:"gpx",text:`<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="Osservatorio Versilia" xmlns="http://www.topografix.com/GPX/1/1">${tracks}</gpx>`}}const placemarks=features.map(f=>{const name=f.properties?.name||"Percorso",geom=geometryLines(f.geometry).map(line=>`<LineString><tessellate>1</tessellate><coordinates>${line.map(c=>`${c[0]},${c[1]},0`).join(" ")}</coordinates></LineString>`).join("");return `<Placemark><name>${xmlEscape(name)}</name><MultiGeometry>${geom}</MultiGeometry></Placemark>`}).join("");return{mime:"application/vnd.google-earth.kml+xml",ext:"kml",text:`<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document>${placemarks}</Document></kml>`}}
function downloadAll(format){if(!state.features.length)return;const payload=collectionPayload(state.features,format);triggerDownload(payload,`percorsi-versilia.${payload.ext}`)}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
document.addEventListener("DOMContentLoaded",()=>{initMap();loadBoundaries();loadData();stabilizeInitialViewport();window.addEventListener("load",stabilizeInitialViewport,{once:true});document.getElementById("search").addEventListener("input",e=>{state.search=e.target.value;applyFilters(false)});document.getElementById("municipality").addEventListener("change",e=>{state.municipality=e.target.value;state.selected=null;document.getElementById("detail").classList.remove("show");applyFilters(true)});document.getElementById("chips").addEventListener("click",e=>{const b=e.target.closest(".chip");if(!b)return;document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.mode=b.dataset.mode;state.selected=null;document.getElementById("detail").classList.remove("show");applyFilters(true)});document.getElementById("reset").addEventListener("click",()=>{state.search="";state.mode="all";state.municipality="";state.selected=null;document.getElementById("detail").classList.remove("show");document.getElementById("search").value="";document.getElementById("municipality").value="";document.querySelectorAll(".chip").forEach(x=>x.classList.toggle("active",x.dataset.mode==="all"));applyFilters(true)});document.getElementById("detailClose").addEventListener("click",()=>clearSelection(true));[["gpxBtn","gpx"],["kmlBtn","kml"],["geoBtn","geojson"]].forEach(([id,fmt])=>document.getElementById(id).addEventListener("click",e=>{e.preventDefault();downloadSelected(fmt)}));[["allGpx","gpx"],["allKml","kml"],["allGeo","geojson"]].forEach(([id,fmt])=>document.getElementById(id).addEventListener("click",e=>{e.preventDefault();downloadAll(fmt)}))});
