"""Independent frozen references and fail-closed commuting semantics."""
import copy
import math

from semantic_query_engine import QueryEngine, ROOT
from test_semantic_query_engine import request, rejected
import semantic_query_commuting_adapters as c

# Transcribed municipal marginals: internal, outgoing, incoming. These are not
# generated by the adapter under test.
REFERENCES = {'046005':(5467,5496,5628), '046013':(925,1056,3364),
              '046018':(2232,5568,1815), '046024':(3688,3848,4349),
              '046028':(1522,2596,1818), '046030':(268,629,174),
              '046033':(12939,7687,7834)}


def regressions(path):
    e = QueryEngine(path,layer='effective'); observations = 0
    for key in c.KEYS:
        result=e.query(request('compare',key)); assert result['status']=='computed',result
        assert len(result['observations'])==7
        for row in result['observations']:
            observations+=1
            internal,outbound,inbound=REFERENCES[row['geography']]
            if key=='inboundCommuters':expected=inbound
            elif key=='outboundCommuters':expected=outbound
            elif key=='commuterBalance':expected=inbound-outbound
            elif key=='selfContainment':expected=internal/(internal+outbound)*100
            else:
                numerator=inbound-outbound if key=='commuterBalanceRate' else inbound if key=='inboundCommutersRate' else outbound
                # Check the denominator independently through known Massarosa
                # snapshots below; all component dates must be declared.
                expected=numerator/row['denominator']*1000
                assert row['numerator']==numerator
                assert row['denominatorPeriod']==('2021' if key=='commuterBalanceRate' else '2026')
            assert math.isclose(row['value'],expected,rel_tol=0,abs_tol=1e-9)
            assert row['source']==c.ARCHIVE and row['period']=='2021'
            assert all(len(ref['sha256'])==64 for ref in row['provenance'])
        rejected(e,request('series',key,towns=['046018']),'commuting_history_not_frozen')
        rejected(e,request('trend',key,towns=['046018']),'commuting_history_not_frozen')
        rejected(e,request('compare',key,periods=['2026']),'commuting_only_2021_frozen')
        rejected(e,request('compare',key,dimension='sex:women'),'dimension_adapter_not_implemented')
        if key in c.RATIOS:
            for code in REFERENCES:
                for scope in ('tuscany','italy'):
                    r=e.query(dict(request('benchmark_gap',key,towns=[code]),benchmark=scope))
                    assert r['status']=='computed',r;observations+=2
        else:
            rejected(e,dict(request('benchmark_gap',key,towns=['046018']),benchmark='tuscany'),'absolute_volume_benchmark_gap_not_supported')
    for key,expected in [('inboundCommutersRate',1815/21782*1000),('outboundCommutersRate',5568/21782*1000),
                         ('commuterBalanceRate',-3753/21951*1000),('selfContainment',2232/7800*100)]:
        r=e.query(request('compare',key,towns=['046018']));assert math.isclose(r['observations'][0]['value'],expected,abs_tol=1e-9)
    for key,n,d,scale in [('inboundCommutersRate',24982,158520,1000),('outboundCommutersRate',26880,158520,1000),
                          ('commuterBalanceRate',-1898,160755,1000),('selfContainment',27041,53921,100)]:
        r=e.query(request('weighted_ratio',key));assert r['status']=='computed',r
        assert r['result']['numerator']==n and r['result']['denominator']==d
        assert math.isclose(r['result']['value'],n/d*scale,abs_tol=1e-9)
    rejected(e,request('compare','outsideMunicipality'),'adapter_not_implemented')
    pair=dict(operation='correlation',selectors=[{'metric':'inboundCommutersRate'},{'metric':'commuterBalanceRate'}],
              axis='municipalities',method='spearman',purpose='Check denominator mismatch, no causal claim')
    rejected(e,pair,'hybrid_denominator_pair_not_aligned')
    pair['selectors'][1]['metric']='outboundCommutersRate';r=e.query(pair)
    assert r['status']=='computed' and r['result']['n']==7 and r['result']['pValue'] is None
    assert math.isclose(r['result']['coefficient'],-17/28,rel_tol=0,abs_tol=1e-12)
    assert 'association_not_causation' in r['warnings']
    pair['selectors']=[{'metric':'selfContainment'},{'metric':'commuterBalance'}]
    r=e.query(pair);assert r['status']=='computed' and r['result']['n']==7,r
    assert math.isclose(r['result']['coefficient'],9/14,rel_tol=0,abs_tol=1e-12)
    # Never replace missing published values with inferred numbers.
    fresh=QueryEngine(path,layer='effective');fresh._catalog['metrics']['selfContainment']['rows'][0]['value']=None
    rows,_=fresh.select({'metric':'selfContainment'},'compare')
    assert any(r['value'] is None and r['dataUnavailable'] for r in rows)
    for alteration,reason in [('value','component_or_value_mismatch'),('identity','geography_identity_changed'),('method','formula_or_universe_changed')]:
        fresh=QueryEngine(path,layer='effective');metric=fresh._catalog['metrics']['inboundCommuters']
        if alteration=='value':metric['rows'][0]['value']+=1
        elif alteration=='identity':metric['rows'][0]['town']='Unknown municipality'
        else:metric['method']['formula']='different universe'
        rejected(fresh,request('compare','inboundCommuters'),reason)
    fresh=QueryEngine(path,layer='effective');snap,ref=fresh.file(c.SNAPSHOT);snap=copy.deepcopy(snap)
    snap['records'][0][2]+=1;fresh.files[c.SNAPSHOT]=(snap,ref)
    rejected(fresh,request('compare','inboundCommuters'),'coverage_or_conservation_changed')
    print(f'A6 commuting regression PASS: {observations} native and benchmark observations; hybrid dates, precision, pooled semantics and refusals verified')


if __name__=='__main__':
    regressions(ROOT/'data/site-data.json')
