"""Independent water pairs, rounded waste references and refusal/adversarial cases."""
import copy
import math

from semantic_query_engine import QueryEngine, ROOT
from test_semantic_query_engine import request, rejected
import semantic_query_environment_adapters as a

# Transcribed input/delivered pairs for 2012, 2015, 2018, not generated by adapter.
WATER = {
    '046005': ((4907,3379),(3744,2598),(4343,2695)),
    '046013': ((3830,2607),(2989,1718),(2763,1648)),
    '046018': ((2361,1637),(2399,1298),(2689,1560)),
    '046024': ((3652,2636),(4363,2100),(3839,2197)),
    '046028': ((1228,825),(1265,674),(1660,795)),
    '046030': ((252,182),(284,149),(389,173)),
    '046033': ((8318,5659),(7250,4660),(6819,4369)),
}
WASTE = {'046005': (753,77.03,343.24), '046013': (1575,77.26,998.69),
         '046018': (603,84.35,275.56), '046024': (876,79.75,360.36),
         '046028': (678,83.76,295.50), '046030': (456,53.86,317.81),
         '046033': (707,69.38,348.20)}
MASSAROSA_WASTE = (650,627,580,585,594,613,584,562,568,549,588,638,576,627,603)
MASSAROSA_RD = (42.25,40.16,38.13,42.59,43.43,44.31,50.68,51.77,60.97,79.6,83.87,85.35,83.95,85.73,84.35)


def regressions(path):
    e = QueryEngine(path, layer='effective')
    count = 0
    for key in a.KEYS:
        result = e.query(request('compare', key))
        assert result['status'] == 'computed', result['reasons']
        assert len(result['observations']) == 7
        for obs in result['observations']:
            code = obs['geography']
            if key == a.WATER:
                n,d = WATER[code][-1]
                expected = (n-d)/n*100
                assert obs['numerator'] == n-d and obs['denominator'] == n
            else:
                waste,rd,cost = WASTE[code]
                expected = rd if key == 'recycling' else waste if key == 'wastePerResident' else cost if key == 'wasteServiceCost' else waste*(1-rd/100)
                assert 'numerator' not in obs and 'denominator' not in obs
            assert math.isclose(obs['value'], expected, rel_tol=0, abs_tol=1e-9)
            assert obs['period'] == ('2018' if key == a.WATER else '2024')
            assert all(len(r['sha256']) == 64 for r in obs['provenance'])
            count += 1
        rejected(e, request('compare', key, dimension='sex:women'), 'dimension_adapter_not_implemented')
        rejected(e, request('compare', key, periods=['2026']), 'environment_period_not_available')
        for scope in ('tuscany', 'italy'):
            r = e.query(dict(request('benchmark_gap', key, towns=['046018']), benchmark=scope))
            assert r['status'] == 'computed', r['reasons']
            count += 2
    for code, pairs in WATER.items():
        r = e.query(request('series', a.WATER, towns=[code]))
        assert r['status'] == 'computed', r['reasons']
        assert [o['period'] for o in r['observations']] == ['2012','2015','2018']
        for o,(n,d) in zip(r['observations'], pairs):
            assert o['numerator'] == n-d and o['denominator'] == n
            assert math.isclose(o['value'], (n-d)/n*100, abs_tol=1e-9)
            count += 1
    for period, n, d in [('2012',7623,24548),('2015',9097,22294),('2018',9065,22502)]:
        r = e.query(request('weighted_ratio', a.WATER, periods=[period]))
        assert r['status'] == 'computed', r['reasons']
        assert r['result']['numerator'] == n and r['result']['denominator'] == d
        assert math.isclose(r['result']['value'], n/d*100, abs_tol=1e-9)
        assert 'water-input weighting' in r['policy']['disjointPopulationEvidence']['method']
    for key in a.WASTE:
        rejected(e, request('weighted_ratio', key), 'verified_ratio_adapter_required')
        for op in ('trend','absolute_change','relative_change','percentage_points'):
            rejected(e, request(op, key, towns=['046018'], periods=['2010','2024']), 'environment_waste_historical_comparability_not_attested')
    for key in ('wastePerResident','recycling','residualWaste'):
        r = e.query(request('series', key, towns=['046018']))
        assert r['status'] == 'computed' and len(r['observations']) == 15
        expected = MASSAROSA_WASTE if key == 'wastePerResident' else MASSAROSA_RD if key == 'recycling' else [w*(1-rd/100) for w,rd in zip(MASSAROSA_WASTE,MASSAROSA_RD)]
        for o,v in zip(r['observations'],expected):
            assert math.isclose(o['value'],v,abs_tol=1e-9)
            count += 1
        assert 'waste_historical_series_does_not_attest_methodological_continuity' in r['warnings']
    r = e.query(request('series','wasteServiceCost',towns=['046018']))
    assert r['status'] == 'computed' and len(r['observations']) == 1
    assert 'service_cost_not_household_tax_or_service_quality' in r['warnings']
    pair = dict(operation='correlation',selectors=[{'metric':'recycling'},{'metric':'residualWaste'}],axis='municipalities',method='spearman',purpose='Inspect mechanically related municipal waste carriers, no causal claim')
    r = e.query(pair)
    assert r['status'] == 'computed' and r['result']['n'] == 7
    assert 'association_not_causation' in r['warnings']
    assert 'environment_shared_components_and_resident_normalization_require_interpretation' in r['warnings']
    pair['axis'] = 'periods'
    for s in pair['selectors']: s.update(towns=['046018'],periods=['2022','2023','2024'])
    rejected(e,pair,'environment_waste_historical_comparability_not_attested')
    # Sparse annual values: no interpolation and no estimate of current 2026 conditions.
    rejected(e,request('compare',a.WATER,periods=['2016']),'environment_period_not_available')
    for mutation,reason in [('unit','environment_definition_or_reference_changed'),('water','environment_catalog_source_mismatch'),('residual','environment_residual_formula_changed'),('missing','partial_coverage_requires_opt_in')]:
        f = QueryEngine(path,layer='effective')
        if mutation == 'unit':f._catalog['metrics'][a.WATER]['meta']['unit']='number'
        elif mutation == 'water':f._catalog['metrics'][a.WATER]['rows'][0]['networkVolumes']['immessa']+=1
        elif mutation == 'residual':f._catalog['metrics']['residualWaste']['method']['formula']='false formula'
        else:f._catalog['metrics'][a.WATER]['rows'][0]['value']=None
        rejected(f,request('compare','residualWaste' if mutation=='residual' else a.WATER),reason)
    f = QueryEngine(path,layer='effective');f._catalog['metrics'][a.WATER]['rows'][0]['value']=None
    rejected(f,request('compare',a.WATER,periods=['2018']),'partial_coverage_requires_opt_in')
    r=f.query(dict(request('weighted_ratio',a.WATER),allowPartial=True))
    assert r['status']=='computed' and len(r['excluded'])==1 and len(r['observations'])==7
    # Tampered raw volumes, metadata, source identity and benchmark gates fail closed.
    for mutate,reason in [('volume','environment_invalid_water_volumes'),('native_share','environment_catalog_source_mismatch'),('flow','environment_water_source_changed')]:
        f=QueryEngine(path,layer='effective');snap,ref=f.file(a.WATER_PATH);snap=copy.deepcopy(snap)
        if mutate=='volume':snap['waterNetworkLosses']['towns']['046018']['2018']['immessa']=0
        elif mutate=='native_share':snap['waterNetworkLosses']['towns']['046018']['2018']['perditePct']+=1
        else:snap['sources']['istat']['flow']='different_flow'
        f.files[a.WATER_PATH]=(snap,ref)
        rejected(f,request('compare',a.WATER),'environment_invalid_water_volumes' if mutate=='volume' else reason)
    for snapshot,key in [(a.WATER_BENCHMARK,a.WATER),(a.WASTE_BENCHMARK,'recycling'),(a.COST_BENCHMARK,'wasteServiceCost')]:
        f=QueryEngine(path,layer='effective');snap,ref=f.file(snapshot);snap=copy.deepcopy(snap);snap['qualityGate']['status']='FAIL';f.files[snapshot]=(snap,ref)
        rejected(f,dict(request('benchmark_gap',key,towns=['046018']),benchmark='tuscany'),'environment_benchmark_gate_changed')
    f=QueryEngine(path,layer='effective');f._catalog['metrics']['recycling']['meta']['benchmark']['tuscany']+=1
    rejected(f,dict(request('benchmark_gap','recycling',towns=['046018']),benchmark='tuscany'),'environment_catalog_source_mismatch')
    print(f'A6 environment PASS: {count} independent current/historical/benchmark observations; water volume weighting, rounded waste components and adversarial refusals verified')


if __name__ == '__main__':
    regressions(ROOT/'dist/data/site-data.json')
